---
- name: dumpall
  hosts: localhost
  tasks:

    - name: Dump all variables
      vars:
        content: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars | to_nice_json }}

          Environment Variables ("environment"):
          --------------------------------
          {{ environment | to_nice_json }}

          GROUP NAMES Variables ("group_names"):
          --------------------------------
          {{ group_names | to_nice_json }}

          GROUPS Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_json }}

          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }}
      debug:
        msg: "{{ content.split('\n') }}"
