---
- name: github_webhook
  hosts: localhost
  tasks:
    - name: Run checks on new pull requests to master
      include_tasks: github_check.yml
      when: >
        tower_webhook_event_type is defined and
        tower_webhook_event_type == "pull_request" and
        tower_webhook_payload is defined and
        tower_webhook_payload.action is defined and
        tower_webhook_payload.action in ["opened", "reopened", "synchronize"] and
        tower_webhook_payload.pull_request is defined and
        tower_webhook_payload.pull_request.base is defined and
        tower_webhook_payload.pull_request.base.ref is defined and
        tower_webhook_payload.pull_request.base.ref == "master"

    - name: Run deployment on pushes to master
      block:
        - include_tasks: github_check.yml
        - include_tasks: github_deploy.yml
      when: >
        tower_webhook_event_type is defined and
        tower_webhook_event_type == "push" and
        tower_webhook_payload is defined and
        tower_webhook_payload.ref is defined and
        tower_webhook_payload.ref == "refs/heads/master"



