---
- name: podman
  hosts: localhost
  collections:
    - containers.podman
  gather_facts: false
  tasks:

    - name: create container build directory
      tempfile:
        state: directory
        suffix: build
      register: tempdir

    - name: copy Dockerfile to remote host
      copy:
        src: "{{ playbook_dir }}/../netcat_container/Dockerfile"
        dest: "{{ tempdir.path }}/Dockerfile"
        mode: 0644

    - name: build the container
      podman_image:
        name: netcat
        path: "{{ tempdir.path }}"

    - name: launch the container
      podman_container:
        name: netcat
        image: netcat
        state: started
        detach: yes
        ports:
          - "1234:1234"

    - add_host:
        name: netcat
        connection: podman
      changed_when: false

- name: podman
  hosts: netcat
  tasks:
    - command: "nc --recv-only localhost 1234"
      register: cmdout
      changed_when: false
    - debug:
        msg: "{{ cmdout.stdout_lines }}"
